import type { ScanResult, Vulnerability } from '../types';

export interface ExportOptions {
  includeBranding: boolean;
  includeSummary: boolean;
  includeVulnerabilities: boolean;
  addWatermark: boolean;
}

const triggerDownload = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Helper to escape CSV fields to handle commas, quotes, and newlines
const escapeCsvField = (field: any): string => {
    const stringField = String(field);
    if (stringField.includes(',') || stringField.includes('"') || stringField.includes('\n')) {
        return `"${stringField.replace(/"/g, '""')}"`;
    }
    return stringField;
}

export const exportToCSV = (result: ScanResult, options: ExportOptions) => {
  let csvContent = '';
  
  if (options.includeBranding) {
    csvContent += 'Report generated by Audityzer PRO\n\n';
  }
  
  if (options.includeSummary) {
    csvContent += 'Severity,Count\n';
    Object.entries(result.summary).forEach(([severity, count]) => {
      csvContent += `${escapeCsvField(severity)},${escapeCsvField(count)}\n`;
    });
    csvContent += '\n';
  }

  if (options.includeVulnerabilities && result.vulnerabilities.length > 0) {
    const headers: (keyof Vulnerability)[] = ['id', 'severity', 'title', 'description', 'recommendation'];
    csvContent += headers.map(escapeCsvField).join(',') + '\n';
    result.vulnerabilities.forEach(vuln => {
      const row = headers.map(header => escapeCsvField(vuln[header]));
      csvContent += row.join(',') + '\n';
    });
  }

  triggerDownload(csvContent, 'audityzer-report.csv', 'text/csv;charset=utf-8;');
};

export const exportToPDF = (result: ScanResult, options: ExportOptions) => {
    let textContent = '';
    const separator = '--------------------------------------------------\n';

    if (options.includeBranding) {
        textContent += 'Audityzer PRO - Smart Contract Scan Report\n';
        textContent += separator;
    }
    
    if (options.addWatermark) {
        textContent += '*** CONFIDENTIAL ***\n\n';
    }

    if (options.includeSummary) {
        textContent += 'Vulnerability Summary\n\n';
        Object.entries(result.summary).forEach(([severity, count]) => {
            textContent += `${severity.charAt(0).toUpperCase() + severity.slice(1)}: ${count}\n`;
        });
        textContent += '\n' + separator;
    }

    if (options.includeVulnerabilities && result.vulnerabilities.length > 0) {
        textContent += 'Detailed Findings\n\n';
        result.vulnerabilities.forEach((vuln, index) => {
            textContent += `Finding ${index + 1}:\n`;
            textContent += `  Title: ${vuln.title}\n`;
            textContent += `  Severity: ${vuln.severity}\n`;
            textContent += `  Description: ${vuln.description}\n`;
            textContent += `  Recommendation: ${vuln.recommendation}\n\n`;
        });
    } else {
        textContent += 'No vulnerabilities found.\n';
    }
    
    if (options.addWatermark) {
        textContent += '\n*** CONFIDENTIAL ***\n';
    }

    // This is a simulation that generates a text file but names it .pdf
    // A full PDF generation would require a library like jsPDF.
    triggerDownload(textContent, 'audityzer-report.pdf', 'text/plain;charset=utf-8;');
};
